Private events - Rails Associations
mohammadumar28/private-events pull request #1
Opened 2020-09-30 15:55 UTC by mohammadumar28

- [ ] Setup project environment
- [ ] Install Styleint and Rubocop
- [ ] Create Models for User, Events and Stats
- [ ] Create Associations between the models
- [ ] Implement Sign up and Login feature
- [ ] Style the views
- [ ] Resolve Rubocop offences

The project requirements have been completed, hence request for the project review.

2020-09-30 17:56 UTC, kubilaycaglayan requested changes
Hello Team 👋
Status: Changes Required ♻️

Great job so far! Your page looks really good. Thanks for spending extra time to add styling. It is easier to navigate through the website... 👍👏

Let's cover some cases together ⏬
All of the checkboxes below are [REQUIRED] except one optional case.

### Controllers
#### events#create

- [ ] uses #build method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

#### users#show
- [x] lists events created by user, i.e. `@created_events =  current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

### No Logic In The Views
💡 Please clean all the logic from the views until none left.

### Database Foreign Keys

- [ ] the events_attendation/events_users/(any other name for join table between users and events) table has column `event_id` of type `integer`
- [ ] the events_attendation/events_users/(any other name for join table between users and events) table has column `user_id` of type `integer`
 💡 Currently you have `attended_event_id`, and `attendee_id` columns. Please change their names accordingly. This change is required for naming conventions. 😇

### Tests
- [ ] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
💡 Please add validation tests. Currently, you have only 8 test cases and all of them are association tests.

- [ ] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
💡 Please add authentication tests.

- [ ] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
💡 Please add tests for event creation.

- [ ] [OPTIONAL] You can add invite feature 😊🎉

#### That's it, team! After you make the changes, you can submit for another code review. ♻️

With all my respect. 🙏

2020-09-30 17:56 UTC, kubilaycaglayan commented on app/views/users/show.html.erb
> +            </div>
:bulb: There shouldn't be any logic in the views 🙏

2020-09-30 17:56 UTC, kubilaycaglayan commented on app/views/users/show.html.erb
> +          <div class="card-body">
:bulb: There shouldn't be any logic in the views :pray:

2020-09-30 17:56 UTC, kubilaycaglayan commented on app/controllers/events_controller.rb
> +    redirect_to @event if @event.save
:bulb: Uses build method.

2020-09-30 17:56 UTC, kubilaycaglayan commented on app/controllers/users_controller.rb
> +  def show; end
:bulb: Let's spice up here according to the requirements, please :pray:

2020-10-02 20:53 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x]  I should be able to attend events created by other users. 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-05 12:33 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Aldana Longhi & Umar Chingani** 
Great job with your new submission :muscle:  :muscle: 
Your page meets most of the requirements :clap: :clap: :clap:  
Just a couple of details to fix:

- [ ] test retrieve of past and upcoming events in your unit tests
- [ ] Your project use yarn so the next command was necessary for me to run your project: 'yarn install --check-files'. In the README file, inside instructions to run locally, add the command.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-10-05 16:28 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

### Hello @mohammadumar28 and @AlduLonghi :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-06 14:05 UTC, merged